devops-apps:
  external-secrets:
    destination:
      cluster: in-cluster
    source:
      repoURL: https://github.com/danielyaba/argocd-app-of-apps

  external-dns:
    destination:
      cluster: in-cluster
    source:
      repoURL: https://github.com/danielyaba/argocd-app-of-apps

  kyverno:
    destination: 
      cluster: in-cluster
    source:
      repoURL: https://github.com/danielyaba/argocd-app-of-apps
    serverSideApply: true

  kyverno-policies:
    destination:
      cluster: in-cluster
    source:
      repoURL: https://github.com/danielyaba/argocd-app-of-apps

  reflector:
    destination:
      cluster: in-cluster
    source: 
      repoURL: https://github.com/danielyaba/argocd-app-of-apps

  sealed-secrets:
    destination:
      cluster: in-cluster
    source: 
      repoURL: https://github.com/danielyaba/argocd-app-of-apps

  cert-manager:
    destination:
      cluster: in-cluster
    source:
      repoURL: https://github.com/danielyaba/argocd-app-of-apps

  grafana:
    destination:
      cluster: in-cluster
    source:
      repoURL: https://github.com/danielyaba/argocd-app-of-apps

  loki:
    destination:
      cluster: in-cluster
    source:
      repoURL: https://github.com/danielyaba/argocd-app-of-apps

  cloudnative-pg:
    destination:
      cluster: in-cluster
    source:
      repoURL: https://github.com/danielyaba/argocd-app-of-apps
