apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: devops-apps-chart
    repoURL: https://source.developers.google.com/p/dgt-gcp-gtst-service-mesh/r/dgt-gcp-gtst-service-mesh
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true