external-apps:
  cloudnative-pg:
    destination:
      cluster: in-cluster
    source: 
      repoURL: https://github.com/danielyaba/argocd-app-of-apps
    serverSideApply: true

  backstage:
    destination:
      cluster: in-cluster
    source:
      repoURL: https://github.com/danielyaba/argocd-app-of-apps