{{- range $key, $value := .Values.devops-apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ $key }}
    name: {{ $value.destination.cluster }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: {{ $value.source.repoURL}}
    targetRevision: HEAD
    path: apps/{{ $value.source.path }}
---
{{- end }}
