apiVersion: v2
name: grafana
description: A Helm chart for grafana
version: 8.10.1
dependencies:
  - name: grafana
    version: 8.10.1
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
