apiVersion: v2
name: backstage
description: A Helm chart for backstage
version: 1.9.5
# appVersion: 1.16.0
dependencies:
  - name: backstage
    version: 1.9.5
    repository: https://backstage.github.io/charts
    condition: backstage.enabled