backstage:
  backstage:
    image:
      registry: danielyaba
      repository: backstage
      tag: 1.0.0
    
    # extraAppConfig:
    #   - filename: app-config.extra.yaml
    #     configMapRef: extra-app-config

    extraEnvVarsSecrets:
      - backstage-secrets

    extraEnvVars:
      - name: POSTGRES_HOST
        value: backstage-rw
      - name: POSTGRES_PORT
        value: "5432"

    appConfig:
      app:
        title: Landing-Zone Backstage App
        baseUrl: http://localhost:7007
        
      organization: 
        name: digital.gov.il

      backend:
        baseUrl: http://localhost:7007
        listen:
          host: localhost
          port: 7007
        database:
          client: pg
          connection:
            host: ${POSTGRES_HOST}
            port: ${POSTGRES_PORT}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}

      integrations:
        github:
          - host: github.com
            token: ${GITHUB_TOKEN}
      
      auth:
        providers:
          guest: {}

      scaffolder:

      techdocs:
        builder: 'local'
      generator:
        runIn: 'local'
      publisher:
        type: 'local'

      catalog:
        locations: []