apiVersion: v1
kind: ConfigMap
metadata:
  name: extra-app-config
  namespace: {{ .Release.Namespace | quote }}
data:
  app-config.extra.yaml: |
    app:
      title: Landing-Zone Backstage App
      
    organization: 
      name: digital.gov.il

    backend:
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

