external-dns:
  image:
    repository: me-west1-docker.pkg.dev/dgt-gcp-gtst-service-mesh/external-dns-images/external-dns

  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: external-dns-sa@dgt-gcp-gtst-service-mesh.iam.gserviceaccount.com
  
  # Specify sources for auto creation of DNS records with external-dns annotation
  # sources:
  #   - service
  #   - ingress

  policy: sync
  
  provider:
    name: google
  extraArgs:
    - --google-project=dgt-gcp-gtst-net-office-0
    - --google-zone-visibility=private
  
  logFormat: json
  domainFilters: 
    - dev.gtst.dgt.gcp.internal
  registry: txt
  txtOwnerId: gke-service-mesh
  txtPrefix: gke-service-mesh-extneral-dns-
