{{- range $key, $value := index .Values "external-apps" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: {{ $value.destination.cluster }}
    namespace: {{ default $key $value.destination.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      {{- if $value.serverSideApply }}
      - ServerSideApply=true
      {{- end }}
  source:
    repoURL: {{ $value.source.repoURL}}
    targetRevision: HEAD
    path: external-apps/{{ $key }}
  {{- with $value.ignoreDependencies }}
  ignoreDifferences:
  {{ toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
