{{-if (index .Values "external-secrets" "secretStore" "gcp").enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: {{ index .Values "external-secrets" "secretStore" "gcp" "projectId" }}
{{- end }}
---
{{-if (index .Values "external-secrets" "secretStore" "aws").enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-store
spec:
  provider:
    aws:
      service: SecretsManager
      role: iam-role
      region: {{ index .Values "external-secrets" "secretStore" "aws" "region" | default "" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: {{ index .Values "external-secrets" "secretStore" "aws" "namespace" | default "" }}
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            namespace: {{ index .Values "external-secrets" "secretStore" "aws" "namespace" | default "" }}
            name: awssm-secret
            key: secret-access-key
{{- end }}

